stages:
  - validate
  - lint
  - render

validate_yaml:
  stage: validate
  image: alpine
  script:
    - apk add --no-cache yamllint
    - yamllint values-prod.yaml
  only:
    - main

helm_lint:
  stage: lint
  image: alpine/helm:3.14.4
  script:
    - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    - helm repo update
    - helm lint prometheus-community/kube-prometheus-stack -f values-prod.yaml
  only:
    - main

lint_scripts:
  stage: lint
  image: koalaman/shellcheck-alpine
  script:
    - shellcheck k3s-bootstrap.sh uninstall.sh scripts/deploy-local.sh scripts/smoke-test.sh
  only:
    - main

render_manifests:
  stage: render
  image: alpine/helm:3.14.4
  script:
    - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    - helm repo update
    - mkdir -p rendered
    - helm template monitor prometheus-community/kube-prometheus-stack -f values-prod.yaml > rendered/monitoring.yaml
  artifacts:
    paths:
      - rendered/monitoring.yaml
    expire_in: 1 week
  only:
    - main
